In [1]:
a=10

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('newer_data.csv')
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [4]:
df.columns

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score', 'total_score', 'average_score'],
      dtype='str')

In [12]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [5]:
X=df[['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course','reading_score',
       'writing_score', 'total_score', 'average_score']]


y=df['math_score']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [8]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [9]:
onehotpreprocessor=OneHotEncoder()
standardpreprocessor=StandardScaler()

In [13]:
cat_features=df.select_dtypes(include=['object','str']).columns
num_features=['reading_score',
       'writing_score', 'total_score', 'average_score']



ct=ColumnTransformer([
    ('OneHotEncoder',onehotpreprocessor,cat_features),
    ('StandardScaler',standardpreprocessor,num_features)
]

)

In [14]:
X_train=ct.fit_transform(X_train)
X_test=ct.transform(X_test)

In [16]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score,root_mean_squared_error,mean_absolute_error,mean_squared_error

In [29]:
models={
    "Random Forest":RandomForestRegressor(),
    "Linear Regression":LinearRegression(),
    "SVM":SVR(),
    "Decision tree":DecisionTreeRegressor(),
    "Adaboost":AdaBoostRegressor(),
    "Xgboost":XGBRegressor(),
    "Gradient boost":GradientBoostingRegressor()
}
model_list=[]
r2_list=[]

for model_name,model in models.items():
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    score=r2_score(y_test,y_pred)

    model_list.append(model_name)
    r2_list.append(score)

    print(f"{model_name}:{score:.4f}")

Random Forest:0.9547
Linear Regression:1.0000
SVM:0.7936
Decision tree:0.9158
Adaboost:0.9126
Xgboost:0.9666
Gradient boost:0.9549

In [30]:
pd.DataFrame(list(zip(model_list,r2_list)),columns=['Model name','R2 Score']).sort_values(by=["R2 Score"],ascending=True)

          Model name  R2 Score
2                SVM  0.793645
4           Adaboost  0.912561
3      Decision tree  0.915813
0      Random Forest  0.954723
6     Gradient boost  0.954870
5            Xgboost  0.966608
1  Linear Regression  1.000000

In [32]:
pred_df=pd.DataFrame({"Actual Value":y_test,"Predicted value":y_pred,"Difference":y_test-y_pred})
pred_df.head()

     Actual Value  Predicted value  Difference
521            91        84.473002    6.526998
737            53        53.250141   -0.250141
740            80        77.995400    2.004600
660            74        74.534519   -0.534519
411            84        84.121985   -0.121985